name: learn-github-actions
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: registry.gitlab.com/atyos/atyosrunner:1.4.1.b39c75ef
    steps:
      - name: git checkout
        id: git-checkout
        uses: actions/checkout@v2

      - name: build, tag and push
        run: |
          #!/bin/bash
          set -eu
          cd components/docker
          bash -c "./build_and_push.sh ${GITHUB_ACTION} ${GITHUB_REF} ${GITHUB_SHA} tdeheurles/aerontest $(cat ../../version.txt) ${{ secrets.DOCKERHUB_USERNAME }} ${{ secrets.DOCKERHUB_TOKEN }}"
