name: learn-github-actions
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: registry.gitlab.com/atyos/atyosrunner:1.4.1.b39c75ef
    steps:
      - name: git checkout
        id: git-checkout
        uses: actions/checkout@v2

      - name: build, tag and push
        run: |
          #!/bin/bash
          set -eu
          cd components/docker

          BUILD_NUMBER:${GITHUB_SHA:0:8} \
          BUILD_PIPELINE=${GITHUB_ACTION} \
          GIT_BRANCH=${GITHUB_REF} \
          GIT_SHORT_SHA=${GITHUB_SHA:0:8} \
          DOCKER_REGISTRY=tdeheurles/aerontest \
          SEMANTIC_VERSIONING=(cat ../../version.txt) \
          DOCKER_USERNAME=${{ secrets.DOCKERHUB_USERNAME }} \
          DOCKER_PASSWORD=${{ secrets.DOCKERHUB_TOKEN }} \
            bash -c ./build_and_push.sh
